#pragma once

#define FALSE 0
#define TRUE 1

#define SUCCESS 0
#define FAILURE 1

#define DEFAULT_MAX_MESSAGE_SIZE 50
#define DEFAULT_MAX_STORAGE_SIZE 30

#define SET_SEND_TIMEOUT 5
#define SET_RECV_TIMEOUT 6
#define REVOKE_DELAYED_MESSAGES 7